name = "riscv_emulator"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["mabeh19"]
maintainers = ["mabeh19 <mathiasibehrens@gmail.com>"]
maintainers-logins = ["mabeh19"]

executables = ["riscv_emulator"]
