with RISCV_Base_Instruction_Format; use RISCV_Base_Instruction_Format;
with RISCV_CPU;

package RISCV_Instruction is

   procedure LB (CPU    : out RISCV_CPU.CPU_Context;
                 Inst   : Instruction);
   --  procedure FENCE (CPU    : out RISCV_CPU.CPU_Context;
   --                   Inst   : Instruction);
   procedure ADDI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure AUIPC (CPU    : out RISCV_CPU.CPU_Context;
                    Inst   : Instruction);
   procedure SB (CPU    : out RISCV_CPU.CPU_Context;
                 Inst   : Instruction);
   procedure ADD (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure LUI (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure BEQ (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure JALR (CPU  : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure JAL (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   --  procedure EBREAK (CPU   : out RISCV_CPU.CPU_Context;
   --                    Inst  : Instruction);
   procedure LH (CPU    : out RISCV_CPU.CPU_Context;
                 Inst   : Instruction);
   --  procedure FENCEI (CPU   : out RISCV_CPU.CPU_Context;
   --                    Inst  : Instruction);
   procedure SLLI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure SH (CPU    : out RISCV_CPU.CPU_Context;
                 Inst   : Instruction);
   procedure SLL (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure BNE (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   --  procedure CSRRW (CPU    : out RISCV_CPU.CPU_Context;
   --                   Inst   : Instruction);
   procedure LW (CPU    : out RISCV_CPU.CPU_Context;
                 Inst   : Instruction);
   procedure SLTI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure SW (CPU    : out RISCV_CPU.CPU_Context;
                 Inst   : Instruction);
   procedure SLT (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   --  procedure CSRRS (CPU    : out RISCV_CPU.CPU_Context;
   --                   Inst   : Instruction);
   procedure SLTIU (CPU    : out RISCV_CPU.CPU_Context;
                    Inst   : Instruction);
   procedure SLTU (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   --  procedure CSRRC (CPU    : out RISCV_CPU.CPU_Context;
   --                   Inst   : Instruction);
   procedure LBU (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure XORI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure INST_XOR (CPU    : out RISCV_CPU.CPU_Context;
                       Inst   : Instruction);
   procedure BLT (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure LHU (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure SRLI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure SRL (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure BGE (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   --  procedure CSRRWI (CPU   : out RISCV_CPU.CPU_Context;
   --                    Inst  : Instruction);
   procedure ORI (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure INST_OR (CPU  : out RISCV_CPU.CPU_Context;
                      Inst : Instruction);
   procedure BLTU (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   --  procedure CSRRSI (CPU   : out RISCV_CPU.CPU_Context;
   --                    Inst  : Instruction);
   procedure ANDI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure INST_AND (CPU    : out RISCV_CPU.CPU_Context;
                       Inst   : Instruction);
   procedure BGEU (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   --  procedure CSRRCI (CPU   : out RISCV_CPU.CPU_Context;
   --                    Inst  : Instruction);
   procedure ECALL (CPU    : out RISCV_CPU.CPU_Context;
                    Inst   : Instruction);
   procedure SUB (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);
   procedure SRAI (CPU  : out RISCV_CPU.CPU_Context;
                   Inst : Instruction);
   procedure SRA (CPU   : out RISCV_CPU.CPU_Context;
                  Inst  : Instruction);

end RISCV_Instruction;
